# This is an incomplete bundle fragment. Do not attempt to deploy.
description: |
    This is a production ready cluster modelled to fit most business needs.
    We start you out with an HA control plane, HA etcd data store, and a load balancer
    to tie it all together.
    Take out all the difficulty of setting up and managing Kubernetes with this bundle,
    ready to deploy, scale, and control the lifecycle management of your containers.
series: xenial
services:
  "kubernetes-master":
    charm: "cs:~containers/kubernetes-master"
    num_units: 1
    options:
      channel: 1.6/stable
    annotations:
      "gui-x": "800"
      "gui-y": "850"
  "kubeapi-load-balancer":
    charm: "cs:~containers/kubeapi-load-balancer"
    num_units: 1
    expose: true
    annotations:
      "gui-x": "450"
      "gui-y": "250"
  "easyrsa":
    charm: "cs:~containers/easyrsa"
    num_units: 1
    annotations:
      "gui-x": "450"
      "gui-y": "550"
  "kubernetes-worker":
    charm: "cs:~containers/kubernetes-worker"
    num_units: 3
    options:
      channel: 1.6/stable
    expose: true
    annotations:
      "gui-x": "100"
      "gui-y": "850"
  "etcd":
    charm: "cs:~containers/etcd"
    num_units: 3
    annotations:
      "gui-x": "800"
      "gui-y": "550"
relations:
  - - "kubernetes-master:kube-api-endpoint"
    - "kubeapi-load-balancer:apiserver"
  - - "kubernetes-master:loadbalancer"
    - "kubeapi-load-balancer:loadbalancer"
  - - "kubernetes-master:kube-control"
    - "kubernetes-worker:kube-control"
  - - "kubernetes-master:certificates"
    - "easyrsa:client"
  - - "etcd:certificates"
    - "easyrsa:client"
  - - "kubernetes-master:etcd"
    - "etcd:db"
  - - "kubernetes-worker:certificates"
    - "easyrsa:client"
  - - "kubernetes-worker:kube-api-endpoint"
    - "kubeapi-load-balancer:website"
  - - "kubeapi-load-balancer:certificates"
    - "easyrsa:client"
