series: xenial
services:
  "kubernetes-master":
    charm: "cs:~containers/kubernetes-master"
    num_units: 1
  "kubeapi-load-balancer":
    charm: "cs:~containers/kubeapi-load-balancer"
    num_units: 1
    expose: true
  "easyrsa":
    charm: "cs:~containers/easyrsa"
    num_units: 1
  "kubernetes-worker":
    charm: "cs:~containers/kubernetes-worker"
    num_units: 3
    expose: true
  "etcd":
    charm: "cs:~containers/etcd"
    num_units: 3
relations:
  - - "kubernetes-master:kube-api-endpoint"
    - "kubeapi-load-balancer:apiserver"
  - - "kubernetes-master:loadbalancer"
    - "kubeapi-load-balancer:loadbalancer"
  - - "kubernetes-master:cluster-dns"
    - "kubernetes-worker:kube-dns"
  - - "kubernetes-master:certificates"
    - "easyrsa:client"
  - - "etcd:certificates"
    - "easyrsa:client"
  - - "kubernetes-master:etcd"
    - "etcd:db"
  - - "kubernetes-worker:certificates"
    - "easyrsa:client"
  - - "kubernetes-worker:kube-api-endpoint"
    - "kubeapi-load-balancer:website"
  - - "kubeapi-load-balancer:certificates"
    - "easyrsa:client"
