series: xenial
services:
  "kubernetes-master":
    charm: "cs:~containers/kubernetes-master"
    num_units: 1
    to:
      - "0"
    expose: true
  "easyrsa":
    charm: "cs:~containers/easyrsa"
    num_units: 1
    to:
      - lxd:0
  "kubernetes-worker":
    charm: "cs:~containers/kubernetes-worker"
    num_units: 1
    to:
      - "1"
    expose: true
  "etcd":
    charm: "cs:~containers/etcd"
    num_units: 1
    to:
      - "0"
relations:
  - - "kubernetes-master:kube-api-endpoint"
    - "kubernetes-worker:kube-api-endpoint"
  - - "kubernetes-master:cluster-dns"
    - "kubernetes-worker:kube-dns"
  - - "kubernetes-master:certificates"
    - "easyrsa:client"
  - - "kubernetes-master:etcd"
    - "etcd:db"
  - - "kubernetes-worker:certificates"
    - "easyrsa:client"
  - - "etcd:certificates"
    - "easyrsa:client"
machines:
  "0":
    series: xenial
  "1":
    series: xenial
